server:
    port: 8080
    address: localhost

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/isag?useSSL=false
        username: root
        password: root

redis:
    ip: 127.0.0.1
    port: 6379
    db: 1
    pwd: Zzjhc123!@#